### ISSUE TITLE
Localisation issues

### ISSUE THREAD

**Issue by AngelTwilight** [Tuesday1028/GTFO_ReceiveAmmoGiveFix#1]
Greetings! It has always been a problem for us that in this mod the phrases are displayed in a Chinese language that we do not understand. All attempts to change the lines to at least English led to nothing. We were never able to change the localization, and we also could not contact Hikaria. Maybe you can help with this problem? Thank you.

**Comment by Mamizu1028** [comment]
> Greetings! It has always been a problem for us that in this mod the phrases are displayed in a Chinese language that we do not understand. All attempts to change the lines to at least English led to nothing. We were never able to change the localization, and we also could not contact Hikaria. Maybe you can help with this problem? Thank you.

Which mods require localization? Currently, all the mods I have created based on TheArchive will have localization support added once I merge the multilingual branch I have written for TheArchive into the mainline. If there are other mods that require localization, please feel free to mention them.

**Comment by AngelTwilight** [comment]
Oh, I just noticed that I made a mistake with the mod page. I'm talking about the old ExchangeItem, it looks simple, but my changes to the text file didn't work.

**Comment by Mamizu1028** [comment]
> Oh, I just noticed that I made a mistake with the mod page. I'm talking about the old ExchangeItem, it looks simple, but my changes to the text file didn't work.

I am planning to rewrite ExchangeItem based on TheArchive. I will do it when I have time.

**Comment by AngelTwilight** [comment]
Got it, thanks for the answer, good luck :3
